# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  android_build:
    macos:
      xcode: "16.1.0"
    steps:
      - checkout
      - run:
          name: install code siginig key for android
          command: | 
            ANDROID_CERTIFICATE_PATH=/Users/distiller/project/mana-key.jks
            echo -n "${AndroidSigning_file}" | base64 --decode -o $ANDROID_CERTIFICATE_PATH
            
      - run:
          name: manage SDK
          command: |
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java 17.0.4.1-tem

      - run:
          name: Install Firebase CLI
          command: curl -sL https://firebase.tools | bash
      
      - run:
          name: Download and Setup Android SDK
          command: |
            # Download Android SDK command-line tools
            curl -o commandlinetools-mac.zip https://dl.google.com/android/repository/commandlinetools-mac-7583922_latest.zip
            
            # Create Android SDK directory
            mkdir -p ~/Library/Android/Sdk/cmdline-tools
            
            # Extract the downloaded tools
            unzip commandlinetools-mac.zip -d ~/Library/Android/Sdk/cmdline-tools
            
            # Move the extracted tools to the correct directory
            mv ~/Library/Android/Sdk/cmdline-tools/cmdline-tools ~/Library/Android/Sdk/cmdline-tools/latest
            
            # Set environment variables
            export ANDROID_HOME=~/Library/Android/Sdk
            export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
            
            # Accept licenses
            yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
            
            # Update SDK tools
            $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update

      - run: 
          name: manage android sdk
          command: |
            ~/Library/Android/Sdk/cmdline-tools/latest/bin/sdkmanager  "tools" "platform-tools" "build-tools;35.0.0" "platforms;android-35"
      - run:
          name: Install .NET SDK
          command: |
            brew install --cask dotnet-sdk
            sudo dotnet workload install maui
      - run:
          name: Build .NET MAUI Project
          command: |
            cd src
            dotnet restore
            dotnet publish -f net9.0-android -c Release /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false
      
      - run:
          name: verify bundle
          command: |
            ls /Users/distiller/project/src/bin/Release/net9.0-android/publish/thes.demo.client-Signed.apk

      - run:
          name: Upload to Firebase
          command: |
            firebase appdistribution:distribute /Users/distiller/project/src/bin/Release/net9.0-android/publish/thes.demo.client-Signed.apk \
              --app 1:353420540110:android:5afe84059ed0b5dba1789f \
              --token 1//0g5o379S6DSXqCgYIARAAGBASNwF-L9IrU5SkAU8vJokJ2iN9ByHCy2JGF8CGACwgJSR9rSkw14MHEV66w-b1LhtjPlPC34voB2Q \
              --groups ManualTester

workflows:
  version: 2
  build_and_test:
    jobs:
      - android_build