  # This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Change ios version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Install .NET MAUI
      run: dotnet workload install maui
      
    - name: Restore dependencies
      run: dotnet restore src/DemoDis.sln

    - name: Build android Platform
      run: |
        cd src
        dotnet publish -f net9.0-android -c Release -p:ArchiveOnBuild=True -p:EnableAssemblyILStripping=false

    - name: Find package
      run: ls /Users/runner/work/DemoDis/DemoDis/src/bin/Release/net9.0-android/publish/thes.demo.client-Signed.apk
        
    - name: Upload to Firebase
      run: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute /Users/runner/work/DemoDis/DemoDis/src/bin/Release/net9.0-android/publish/thes.demo.client-Signed.aab \
            --app 1:353420540110:android:5afe84059ed0b5dba1789f \
            --token 1//0g5o379S6DSXqCgYIARAAGBASNwF-L9IrU5SkAU8vJokJ2iN9ByHCy2JGF8CGACwgJSR9rSkw14MHEV66w-b1LhtjPlPC34voB2Q \
            --groups ManualTester
    
    # - name: Upload a android Build Artifact
    #   uses: actions/upload-artifact@v3.0.0
    #   with:
    #     path: '**/*.aab'
